apiVersion: apps/v1
kind: Deployment
metadata:
    name: note
spec:
    replicas: 1
    selector:
        matchLabels:
            app: note
    template:
        metadata:
            labels:
                app: note
        spec:
            containers:
                - name: note
                  image: partage-note-api:latest
                  imagePullPolicy: IfNotPresent
                  resources:
                      requests:
                          cpu: 100m
                          memory: 128Mi
                      limits:
                          cpu: 250m
                          memory: 256Mi
                  ports:
                      - name: http
                        containerPort: 80
